---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{.NetAttachDefName}}
  namespace: {{getOr . "NetAttachDefNamespace" "default"}}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/{{.InterfaceName}}
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ovs",
    "bridge": "{{.InterfaceName}}",
    "vlan": {{.AccessVlan}}
  }'
