---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{.NetAttachDefName}}
  namespace: {{getOr . "NetAttachDefNamespace" "default"}}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/{{.NetObjName}}
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ovs",
{{if (index . "AccessVlan") }}
    "vlan": {{.AccessVlan}},
{{end}}{{if (index . "SelectiveVlan") }}
    "trunk": {{.SelectiveVlan}},
{{end}}
    "bridge": "{{.NetObjName}}",
{{if (index . "Ipam") }}
    "ipam" :{{.Ipam}}
{{end}}
  }'
