apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-ten
spec:
  SegmentationID: 10
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-eleven
spec:
  SegmentationID: 11
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-twelve
spec:
  SegmentationID: 12
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-thirteen
spec:
  SegmentationID: 13
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-fourteen
spec:
  SegmentationID: 14
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-fifteen
spec:
  SegmentationID: 15
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-sixteen
spec:
  SegmentationID: 16
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-seventeen
spec:
  SegmentationID: 17
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-eighteen
spec:
  SegmentationID: 18
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-nineteen
spec:
  SegmentationID: 19
  PhysicalNet: ["PhysDC"]
---
apiVersion: eno.k8s.io/v1alpha1
kind: L2Service
metadata:
  name: l2service-twenty
spec:
  SegmentationID: 20
  PhysicalNet: ["PhysDC"]