apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ovs-fabric-plugin-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ovs-fabric-plugin-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
