apiVersion: eno.k8s.io/v1alpha1
kind: L2ServiceAttachment
metadata:
  name: ovs-selective
  namespace: test
spec:
  L2Services:
    - "l2service-ten"
    - "l2service-eleven"
    - "l2service-twelve"
    - "l2service-thirteen"
    - "l2service-fourteen"
  ConnectionPoint: "cp-br-data"
  PodInterfaceType: "kernel"
  Implementation: "ovs"
  VlanType: "selectivetrunk"
