apiVersion: v1
kind: ConfigMap
metadata:
  name: pool-conf
  #namespace: system
  namespace: test
data:
  nodePools: |
    - poolConf:
        name: ovs-pool
        netConf:
          interfaces:
            - name: ens3
              type: ethernet
              state: up
            - name: ens4
              type: ethernet
              state: up
            - name: ens5
              type: ethernet
              state: up
            - name: ens6
              type: ethernet
              state: up
            - name: ens26
              type: ethernet
              state: up
              connectionPoint: cp-br-data
            - name: ens27
              type: ethernet
              state: up
              connectionPoint: cp-br-trunk
    - poolConf:
        name: virtio-pool
        netConf:
          interfaces:
            - name: ens3
              type: ethernet
              state: up
            - name: ens4
              type: ethernet
              state: up
            - name: ens5
              type: ethernet
              state: up
            - name: ens6
              type: ethernet
              state: up
            - name: ens10
              type: ethernet
              state: up
              connectionPoint: cp-virtio
            - name: ens11
              type: ethernet
              state: up
              connectionPoint: cp-virtio
            - name: ens12
              type: ethernet
              state: up
              connectionPoint: cp-virtio
            - name: ens13
              type: ethernet
              state: up
              connectionPoint: cp-virtio
