# permissions for end users to view connectionpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connectionpoint-viewer-role
rules:
- apiGroups:
  - eno.k8s.io
  resources:
  - connectionpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eno.k8s.io
  resources:
  - connectionpoints/status
  verbs:
  - get
