# permissions for end users to edit connectionpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connectionpoint-editor-role
rules:
- apiGroups:
  - eno.k8s.io
  resources:
  - connectionpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eno.k8s.io
  resources:
  - connectionpoints/status
  verbs:
  - get
