# permissions for end users to view l2services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: l2service-viewer-role
rules:
- apiGroups:
  - eno.k8s.io
  resources:
  - l2services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eno.k8s.io
  resources:
  - l2services/status
  verbs:
  - get
