# permissions for end users to view l2serviceattachments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: l2serviceattachment-viewer-role
rules:
- apiGroups:
  - eno.k8s.io
  resources:
  - l2serviceattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eno.k8s.io
  resources:
  - l2serviceattachments/status
  verbs:
  - get
