
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eno.k8s.io
  resources:
  - connectionpoints
  - l2services
  - routes
  - subnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eno.k8s.io
  resources:
  - l2bridgedomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eno.k8s.io
  resources:
  - l2serviceattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eno.k8s.io
  resources:
  - l2serviceattachments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eno.k8s.io
  resources:
  - l2services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eno.k8s.io
  resources:
  - l2services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - '*'
  verbs:
  - '*'
