apiVersion: eno.k8s.io/v1alpha1
kind: Subnet
metadata:
  name: ipv4-subnet
spec:
  Address: "10.10.1.0"
  Mask: 24
  AllocationPool: [{"Start":"10.10.1.10","End":"10.10.1.255"}]
  Ipam: "whereabouts"
  Routes: ["ipv4-subnet1-route"]
  #DNS:
  Type: "v4"