# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/eno.k8s.io_l2serviceattachments.yaml
- bases/eno.k8s.io_connectionpoints.yaml
- bases/eno.k8s.io_l2services.yaml
- bases/eno.k8s.io_subnets.yaml
- bases/eno.k8s.io_routes.yaml
- bases/eno.k8s.io_l2bridgedomains.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_l2serviceattachments.yaml
#- patches/webhook_in_connectionpoints.yaml
#- patches/webhook_in_l2services.yaml
#- patches/webhook_in_subnets.yaml
#- patches/webhook_in_routes.yaml
#- patches/webhook_in_l2bridgedomains.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_l2serviceattachments.yaml
#- patches/cainjection_in_connectionpoints.yaml
#- patches/cainjection_in_l2services.yaml
#- patches/cainjection_in_subnets.yaml
#- patches/cainjection_in_routes.yaml
#- patches/cainjection_in_l2bridgedomains.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
