apiVersion: eno.k8s.io/v1alpha1
kind: ConnectionPoint
metadata:
  name: cp-br-data
spec:
  Description: "Represents the br-data OvS bridge"
  SupportedCnis:
    - Name: "ovs"
      SupportedInterfaceTypes: ["kernel"]
      Opts: '{
        "BridgeName": "br-data"
        }'
