apiVersion: eno.k8s.io/v1alpha1
kind: ConnectionPoint
metadata:
  name: cp-br-trunk
spec:
  Description: "Represents the br-trunk OvS bridge"
  SupportedCnis:
    - Name: "ovs"
      SupportedInterfaceTypes: ["kernel"]
      Opts: '{
        "BridgeName": "br-trunk"
        }'
