apiVersion: eno.k8s.io/v1alpha1
kind: ConnectionPoint
metadata:
  name: cp-virtio
spec:
  Type: "pcidev"
  NodePool: "virtio-pool"
  PhysicalNet: "virtio-physnet"
  ResourceName: "intel.com/virtio_net_device"